// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAttY7PSJDGCZ3EHHY54RwqOufbKwpUqdI',
    appId: '1:902031588283:web:de0bdd857e1aeb05a9229e',
    messagingSenderId: '902031588283',
    projectId: 'e-commers-e2638',
    authDomain: 'e-commers-e2638.firebaseapp.com',
    storageBucket: 'e-commers-e2638.appspot.com',
    measurementId: 'G-DN5MNZXGRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxSwUrIFIV7KkGYQ52RHCgEhwP5_qqvzw',
    appId: '1:902031588283:android:2d80d59360f7184ba9229e',
    messagingSenderId: '902031588283',
    projectId: 'e-commers-e2638',
    storageBucket: 'e-commers-e2638.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgsUWekj2K9VQlYLj-8ASBS0F_VXwLNkw',
    appId: '1:902031588283:ios:d7dc3fa8d8862320a9229e',
    messagingSenderId: '902031588283',
    projectId: 'e-commers-e2638',
    storageBucket: 'e-commers-e2638.appspot.com',
    iosClientId: '902031588283-gq85a9idn8svfd424odcdma8b6eepppg.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgsUWekj2K9VQlYLj-8ASBS0F_VXwLNkw',
    appId: '1:902031588283:ios:d7dc3fa8d8862320a9229e',
    messagingSenderId: '902031588283',
    projectId: 'e-commers-e2638',
    storageBucket: 'e-commers-e2638.appspot.com',
    iosClientId: '902031588283-gq85a9idn8svfd424odcdma8b6eepppg.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommers',
  );
}
